name         = "Catppuccin Frappé"
bg           = "#303446"
fg           = "#c6d0f5"
dim          = "#737994"
accent       = "#ca9ee6"
highlight    = "#414559"
selected_fg  = "#f2d5cf"
success      = "#a6d189"
warn         = "#e5c890"
error        = "#e78284"
running      = "#8caaee"
info         = "#85c1dc"
badge_bg     = "#414559"
badge_fg     = "#c6d0f5"
