name: Nix
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  flake-check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: flake check
        run: nix flake check --print-build-logs --accept-flake-config
      - name: build package
        run: nix build .#lazyjust --print-build-logs --accept-flake-config
      - name: smoke test
        run: ./result/bin/lazyjust --version
